/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsOlympicLiftingRouteImport } from './routes/workouts_.olympic-lifting'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsOlympicLiftingRoute = WorkoutsOlympicLiftingRouteImport.update({
  id: '/workouts_/olympic-lifting',
  path: '/workouts/olympic-lifting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/workouts/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/workouts/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/workouts_/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/nutrition' | '/routines' | '/workouts' | '/workouts/olympic-lifting'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/nutrition' | '/routines' | '/workouts' | '/workouts/olympic-lifting'
  id:
    | '__root__'
    | '/'
    | '/nutrition'
    | '/routines'
    | '/workouts'
    | '/workouts_/olympic-lifting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NutritionRoute: typeof NutritionRoute
  RoutinesRoute: typeof RoutinesRoute
  WorkoutsRoute: typeof WorkoutsRoute
  WorkoutsOlympicLiftingRoute: typeof WorkoutsOlympicLiftingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts_/olympic-lifting': {
      id: '/workouts_/olympic-lifting'
      path: '/workouts/olympic-lifting'
      fullPath: '/workouts/olympic-lifting'
      preLoaderRoute: typeof WorkoutsOlympicLiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NutritionRoute: NutritionRoute,
  RoutinesRoute: RoutinesRoute,
  WorkoutsRoute: WorkoutsRoute,
  WorkoutsOlympicLiftingRoute: WorkoutsOlympicLiftingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
