/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsOlympicLiftingRouteImport } from './routes/workouts_.olympic-lifting'
import { Route as PlansMemberRouteImport } from './routes/plans.$member'
import { Route as PlansMemberIndexRouteImport } from './routes/plans.$member.index'
import { Route as PlansMemberWorkoutsRouteImport } from './routes/plans.$member.workouts'
import { Route as PlansMemberRoutinesRouteImport } from './routes/plans.$member.routines'
import { Route as PlansMemberNutritionRouteImport } from './routes/plans.$member.nutrition'
import { Route as PlansMemberWorkoutsOlympicLiftingRouteImport } from './routes/plans.$member.workouts_.olympic-lifting'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsOlympicLiftingRoute = WorkoutsOlympicLiftingRouteImport.update({
  id: '/workouts_/olympic-lifting',
  path: '/workouts/olympic-lifting',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMemberRoute = PlansMemberRouteImport.update({
  id: '/plans/$member',
  path: '/plans/$member',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansMemberIndexRoute = PlansMemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansMemberRoute,
} as any)
const PlansMemberWorkoutsRoute = PlansMemberWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => PlansMemberRoute,
} as any)
const PlansMemberRoutinesRoute = PlansMemberRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => PlansMemberRoute,
} as any)
const PlansMemberNutritionRoute = PlansMemberNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => PlansMemberRoute,
} as any)
const PlansMemberWorkoutsOlympicLiftingRoute =
  PlansMemberWorkoutsOlympicLiftingRouteImport.update({
    id: '/workouts_/olympic-lifting',
    path: '/workouts/olympic-lifting',
    getParentRoute: () => PlansMemberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/plans/$member': typeof PlansMemberRouteWithChildren
  '/workouts/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
  '/plans/$member/nutrition': typeof PlansMemberNutritionRoute
  '/plans/$member/routines': typeof PlansMemberRoutinesRoute
  '/plans/$member/workouts': typeof PlansMemberWorkoutsRoute
  '/plans/$member/': typeof PlansMemberIndexRoute
  '/plans/$member/workouts/olympic-lifting': typeof PlansMemberWorkoutsOlympicLiftingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/workouts/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
  '/plans/$member/nutrition': typeof PlansMemberNutritionRoute
  '/plans/$member/routines': typeof PlansMemberRoutinesRoute
  '/plans/$member/workouts': typeof PlansMemberWorkoutsRoute
  '/plans/$member': typeof PlansMemberIndexRoute
  '/plans/$member/workouts/olympic-lifting': typeof PlansMemberWorkoutsOlympicLiftingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionRoute
  '/routines': typeof RoutinesRoute
  '/workouts': typeof WorkoutsRoute
  '/plans/$member': typeof PlansMemberRouteWithChildren
  '/workouts_/olympic-lifting': typeof WorkoutsOlympicLiftingRoute
  '/plans/$member/nutrition': typeof PlansMemberNutritionRoute
  '/plans/$member/routines': typeof PlansMemberRoutinesRoute
  '/plans/$member/workouts': typeof PlansMemberWorkoutsRoute
  '/plans/$member/': typeof PlansMemberIndexRoute
  '/plans/$member/workouts_/olympic-lifting': typeof PlansMemberWorkoutsOlympicLiftingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nutrition'
    | '/routines'
    | '/workouts'
    | '/plans/$member'
    | '/workouts/olympic-lifting'
    | '/plans/$member/nutrition'
    | '/plans/$member/routines'
    | '/plans/$member/workouts'
    | '/plans/$member/'
    | '/plans/$member/workouts/olympic-lifting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nutrition'
    | '/routines'
    | '/workouts'
    | '/workouts/olympic-lifting'
    | '/plans/$member/nutrition'
    | '/plans/$member/routines'
    | '/plans/$member/workouts'
    | '/plans/$member'
    | '/plans/$member/workouts/olympic-lifting'
  id:
    | '__root__'
    | '/'
    | '/nutrition'
    | '/routines'
    | '/workouts'
    | '/plans/$member'
    | '/workouts_/olympic-lifting'
    | '/plans/$member/nutrition'
    | '/plans/$member/routines'
    | '/plans/$member/workouts'
    | '/plans/$member/'
    | '/plans/$member/workouts_/olympic-lifting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NutritionRoute: typeof NutritionRoute
  RoutinesRoute: typeof RoutinesRoute
  WorkoutsRoute: typeof WorkoutsRoute
  PlansMemberRoute: typeof PlansMemberRouteWithChildren
  WorkoutsOlympicLiftingRoute: typeof WorkoutsOlympicLiftingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts_/olympic-lifting': {
      id: '/workouts_/olympic-lifting'
      path: '/workouts/olympic-lifting'
      fullPath: '/workouts/olympic-lifting'
      preLoaderRoute: typeof WorkoutsOlympicLiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$member': {
      id: '/plans/$member'
      path: '/plans/$member'
      fullPath: '/plans/$member'
      preLoaderRoute: typeof PlansMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$member/': {
      id: '/plans/$member/'
      path: '/'
      fullPath: '/plans/$member/'
      preLoaderRoute: typeof PlansMemberIndexRouteImport
      parentRoute: typeof PlansMemberRoute
    }
    '/plans/$member/workouts': {
      id: '/plans/$member/workouts'
      path: '/workouts'
      fullPath: '/plans/$member/workouts'
      preLoaderRoute: typeof PlansMemberWorkoutsRouteImport
      parentRoute: typeof PlansMemberRoute
    }
    '/plans/$member/routines': {
      id: '/plans/$member/routines'
      path: '/routines'
      fullPath: '/plans/$member/routines'
      preLoaderRoute: typeof PlansMemberRoutinesRouteImport
      parentRoute: typeof PlansMemberRoute
    }
    '/plans/$member/nutrition': {
      id: '/plans/$member/nutrition'
      path: '/nutrition'
      fullPath: '/plans/$member/nutrition'
      preLoaderRoute: typeof PlansMemberNutritionRouteImport
      parentRoute: typeof PlansMemberRoute
    }
    '/plans/$member/workouts_/olympic-lifting': {
      id: '/plans/$member/workouts_/olympic-lifting'
      path: '/workouts/olympic-lifting'
      fullPath: '/plans/$member/workouts/olympic-lifting'
      preLoaderRoute: typeof PlansMemberWorkoutsOlympicLiftingRouteImport
      parentRoute: typeof PlansMemberRoute
    }
  }
}

interface PlansMemberRouteChildren {
  PlansMemberNutritionRoute: typeof PlansMemberNutritionRoute
  PlansMemberRoutinesRoute: typeof PlansMemberRoutinesRoute
  PlansMemberWorkoutsRoute: typeof PlansMemberWorkoutsRoute
  PlansMemberIndexRoute: typeof PlansMemberIndexRoute
  PlansMemberWorkoutsOlympicLiftingRoute: typeof PlansMemberWorkoutsOlympicLiftingRoute
}

const PlansMemberRouteChildren: PlansMemberRouteChildren = {
  PlansMemberNutritionRoute: PlansMemberNutritionRoute,
  PlansMemberRoutinesRoute: PlansMemberRoutinesRoute,
  PlansMemberWorkoutsRoute: PlansMemberWorkoutsRoute,
  PlansMemberIndexRoute: PlansMemberIndexRoute,
  PlansMemberWorkoutsOlympicLiftingRoute:
    PlansMemberWorkoutsOlympicLiftingRoute,
}

const PlansMemberRouteWithChildren = PlansMemberRoute._addFileChildren(
  PlansMemberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NutritionRoute: NutritionRoute,
  RoutinesRoute: RoutinesRoute,
  WorkoutsRoute: WorkoutsRoute,
  PlansMemberRoute: PlansMemberRouteWithChildren,
  WorkoutsOlympicLiftingRoute: WorkoutsOlympicLiftingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
